### ISSUE TITLE
relative path to local images is not working

### ISSUE THREAD

**Issue by JulioCVaz** [robin-dela/hover-effect#11]
Hi.

Congratulations for the tool!! Is so amazing.

I'm with problem. Relative path to local images is not working.

**Exemple**: 

new hoverEffect({
    parent: document.querySelector('.ticket'),
    intensity1: 0.1,
    intensity2: 0.1,
    // angle2: Math.PI / 2,
    image1: "../images/balloon.jpg",

I imported the lib imagesloaded, but not working. Only function with images uploaded from websites.

**Comment by robin-dela** [comment]
Hi,

You need to run a local server to access the images, you can do that by running this command: `python -m SimpleHTTPServer 8000` 
or installing [http-server](https://github.com/indexzero/http-server)

**Comment by JulioCVaz** [comment]
Ok, thanks!

**Comment by HeuSalander** [comment]
Hello Robin great work with this lib. 

Im having the same problem with the images not showing up, im running node js and it gives me a local server and everything but images still don't showing up, it only works with images from other servers.

I don't know what im missing

`
        new hoverEffect({
            parent: document.querySelector('.imagewrapper'),
            intensity: 0.3,
            image1: './img_two.jpg',
            image2: './img_one.jpg',
            displacementImage: './4.png'
        });
`

Thx for any help!
