### ISSUE TITLE
canvas defaults height to 0

### ISSUE THREAD

**Issue by MrBushid0** [robin-dela/hover-effect#18]
Hi,

I'm trying to implement this helper in WP on a site using elementor. I copy pasted the example code to test and only changed the imgs, displacement img paths. Yet the canvas that's generated always has 0 height.

If i add a canvas element inside the div, it works. However, i end up with 2 canvas elements creating a white space above the auto-generated canvas which contains the images and hovering on that space changes images as well...

Any guidance is much appreciated.

Thanks

**Comment by robin-dela** [comment]
Hey,

What is the size of your parent div? The way this helper is working is using the parent's height and width to generate the Canvas, so if your div has nothing inside and no style: a width and height of 0, the generated canvas will have a height of 0 as well.

If that's not the case please share some more code so I can investigate this issue.

Cheers

**Comment by MrBushid0** [comment]
Hi,

That was the problem indeed. Thank you for the prompt reply!

Best
