### ISSUE TITLE
Can't use videos because of autoplay policy

### ISSUE THREAD

**Issue by wevdevaleksei** [robin-dela/hover-effect#19]
Is there a possibility to add "muted" to the videos when i want to use them instead of images. It works on my localhost just fine, but because of the new policy if i upload it wont show the videos.

and i have these errors in console:

256WebGL: INVALID_VALUE: tex(Sub)Image2D: video visible size is empty
2hover-effect.umd.js:1 Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD

Maybe there is a way to overcome this? 

Would appreciate any suggestions :)

**Comment by lucrampro** [comment]
for use video you must declare the video in mute = true

**Comment by robin-dela** [comment]
Fixed with the new version (videos are muted by default now)
