### ISSUE TITLE
Change angle

### ISSUE THREAD

**Issue by paulzz3000** [robin-dela/hover-effect#2]
I can't get the angle set so the effect falls downwards.

**Comment by robin-dela** [comment]
Hey,
by setting the angles to: 

```
angle1: -Math.PI / 2,
angle2: Math.PI / 2
```

The effect go downwards like in this gif:

![aug-15-2018 14-37-05](https://user-images.githubusercontent.com/8898989/44148443-b584fe58-a098-11e8-9f53-61126eee4d68.gif)

**Comment by jerusking** [comment]
Hi Robin,

Would like to know if theres a way to auto distort the image? Like a gallery when hover the button the image appears and distort automatically? Please see image below illustration. Your help is highly appreciated.
![8](https://user-images.githubusercontent.com/41040925/44360145-cd265780-a46e-11e8-85d2-d8dfe869d7c8.jpg)

Many thanks,

Jerus

**Comment by robin-dela** [comment]
Hi @jerusking please open your own issue, I'll close this one.
