### ISSUE TITLE
How to get this to work on NPM?

### ISSUE THREAD

**Issue by Seeingred0** [robin-dela/hover-effect#39]
I'm setting up on JS file as the following, however I'm getting an issue - Uncaught TypeError: Cannot read property 'greensock' of undefined

Here's my JS code:

    import { hoverEffect } from 'hover-effect';

    new hoverEffect({

    parent: document.querySelector('.img'),
    intensity: 0.3,
    image1: './1.jpg',
    image2: './2.jpg',
    displacementImage: './4.png'

})

**Comment by robin-dela** [comment]
Fixed with the new version (updated GSAP dependency to the last version)
