### ISSUE TITLE
Force hover on-load

### ISSUE THREAD

**Issue by elliott-impression** [robin-dela/hover-effect#4]
Hey,

I am trying to use reuse this fantastic hover-effect solution so that rather than on hover, I get the same effect on page load. A similar example (without the slider) would be: https://yard.agency/en.

My initial thought would be to force hover on the element, using jQuery methods like below:
```
// 01. Document ready
$(document).ready(function(){
        $("figure.my-element").trigger('mouseenter');
});

// 02. Window load
$(window).load(function(){
        $("figure.my-element").trigger('mouseenter');
});

// 03. Timeout
setTimeout(function(){
        $("figure.my-element").trigger('mouseenter');
}, 2000);
```

Unfortunately, none of the above appear to work, and I wonder if you can shed a simple solution that will help me achieve this load-in effect.

Thank you and great job!

**Comment by robin-dela** [comment]
Hey Elliott,

You can use the next method after the load of the page to trigger the effect.

I've done a quick test and something like this works:

`$(document).ready(function(){
	myHoverEffect.next();
});`

Let me know if this works for you

**Comment by elliott-impression** [comment]
@robin-dela this works a dream. Thanks so much for the speedy response, really appreciate the support!
