### ISSUE TITLE
Disable hover effect

### ISSUE THREAD

**Issue by elliott-impression** [robin-dela/hover-effect#5]
Hey,

After using `.next();` (as per #4) to animate the effect document load, I'm now hoping to prevent any more transitions when hovering over this particular element.

Effectively I'm hoping to achieve:
- A user enters website and the animation (using `.next()`) takes place once.
- When the user hovers on/off the element after the above, I don't want the animation to take place.

Is there some way of easily destroying/preventing hover-effect, i.e. after an interval? 

I need the image (2nd) to still be visible, just no hovering effects.

Thank you and kindest regards,
Elliott

**Comment by robin-dela** [comment]
Hey,

you can set the hover parameters to false when creating your effect: `myHoverEffect = new hoverEffect({ hover: false })`

**Comment by elliott-impression** [comment]
This worked a dream! Thanks for the speedy support yet again 😃

**Comment by Ahmad-Hendi** [comment]
Hello ,

I would like to use next() method but i don’t know how , i checked the document of @robin-dela but i didn’t understand how ):

can you explain to me how can i use it ?

Thanks in advance
