### ISSUE TITLE
Canvas Image not loading 

### ISSUE THREAD

**Issue by hendrikbrueggemann** [robin-dela/hover-effect#58]
Hey, ive looked many hours into my code and tried a lot, but unfortunatly the canvas will not load the image. Its injected but it does not show any color or image.

https://preace.de/ PW: heik0

I would appreciate any suggestions.

**Comment by robin-dela** [comment]
Hey,
I can't really help you without any code but I looked at your website quickly and I suggest having a look at the timing around instantiating. When I run the hover script once your website is fully loaded the canvas is showing and working (see screenshot below) so maybe something is blocking the execution of the script.


<img width="1115" alt="Screenshot 2023-02-22 at 1 43 01 pm" src="https://user-images.githubusercontent.com/8898989/220507788-ceb686ba-fc57-4d23-bfae-c47fb9e81607.png">

**Comment by hendrikbrueggemann** [comment]
Hey Robin,

thank you so much for taking your time! As you said, there was some third party script which blocked the function.

Really appreciated.
