### ISSUE TITLE
Possible to make it work with videos?

### ISSUE THREAD

**Issue by pedro-rivera** [robin-dela/hover-effect#6]
Hey, I was playing around with this amazing demo and trying to make it work with videos.

I changed the querySelectorAll from img to video and every other things related to img tags, on js and css files, but whatever I do the console says

`Uncaught TypeError: Cannot read property 'getAttribute' of undefined`

If I log the imgs[0].getAttribute('src'), it returns the video url instead :(

Any ideas?

**Comment by robin-dela** [comment]
Hey @pedro-rivera sorry for the delay!

I've updated the library, it supports videos now :) 

Cheers
