### ISSUE TITLE
CORS Policy?

### ISSUE THREAD

**Issue by rudrathegreat** [robin-dela/hover-effect#62]
Why so many errors! I remember this working first time and now I can't even get past all the errors and get a basic tutorial working (which I copied and pasted to make sure I wasn't the one making mistakes)

What is this error now?!

```

Access to image [image file path] from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, isolated-app, chrome-extension, chrome-untrusted, https, edge.

```

**Comment by robin-dela** [comment]
Dude stop spamming, you opened and closed 3 issues in less than one hour before even googling the error you're getting. That one is pretty self-explanatory, I invite you to google it as well...
